<a href="https://colab.research.google.com/github/CoffeE23/ML-Projects/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Dataset

In [ ]:
#Load the data from scikit
from sklearn.datasets import load_iris
data = load_iris()

In [ ]:
#Look at the information of data
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
#If want to convert this data from scikit in pandas dataframe
# import numpy as np
# import pandas as pd
# data1 = pd.DataFrame(data= np.c_[data['data'], data['target']],
#                      columns= data['feature_names'] + ['target'])
# data1.head()

In [ ]:
#Dividing the data into independant and dependant sets
X = data.data
Y = data.target

## Train-Test Split

In [ ]:
#Dividing data in training and testing datasets
from sklearn.model_selection import train_test_split
# print(train_test_split.__doc__)
Xtrn, Xtst, Ytrn, Ytst = train_test_split(X,Y, train_size = 0.8, random_state = 100)

In [ ]:
print(Xtrn.shape)
print(Ytrn.shape)
print(Xtst.shape)
print(Ytst.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [ ]:
Ytrn.ndim

1

## Training Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(Xtrn,Ytrn)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Evaluation of model

In [ ]:
Ypred = model.predict(Xtst)

In [ ]:
print(Ytst)
print(Ypred)

[2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 1 2 2 2 0 2 0 1 2 1 0 1 2]
[2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 2 2 2 2 0 2 0 1 2 1 0 1 2]


### 1.Accuracy

In [ ]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(Ytst,Ypred)
acc

0.9666666666666667

### 2.Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix
# print(confusion_matrix.__doc__)
# columns represent Predicted class, Rows represent Actual Class
cm = confusion_matrix(Ytst,Ypred,labels=[0,1,2])
cm

array([[11,  0,  0],
       [ 0,  5,  1],
       [ 0,  0, 13]])

### 3.Recall Matrix

In [ ]:
# #Predicted/ #Actual class
rm =(((cm.T)/(cm.sum(axis=1))).T) #Recall
rm

array([[1.        , 0.        , 0.        ],
       [0.        , 0.83333333, 0.16666667],
       [0.        , 0.        , 1.        ]])

In [ ]:
from sklearn.metrics import recall_score
rec = recall_score(Ytst,Ypred, average = 'micro')
rec

0.9666666666666667

### 4.Precision Matrix

In [ ]:
# #Actual Class/ #Prediction
pm =(cm/cm.sum(axis=0)) #Precision 
pm

array([[1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.07142857],
       [0.        , 0.        , 0.92857143]])

In [ ]:
from sklearn.metrics import precision_score
prec = precision_score(Ytst,Ypred, average = 'micro')
prec

0.9666666666666667

### 5.F1 Score

In [ ]:
F1 = 2*pm*rm/(pm+rm)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
from sklearn.metrics import f1_score
f1 = f1_score(Ytst,Ypred, average = 'micro')
f1

0.9666666666666667